Repository terraform-providers/terraform-provider-rightscale, pull requests merged in 2018-09, with the labels that each got.

#1 rightscale -> terraform-providers
  CHANGELOG.md
  README.md
  main.go
  rightscale/cm_helpers.go
  rightscale/data_source_cloud.go
  rightscale/data_source_credential.go
  rightscale/data_source_datacenter.go
  rightscale/data_source_deployment.go
  rightscale/data_source_image.go
  rightscale/data_source_instance.go
  rightscale/data_source_instance_type.go
  rightscale/data_source_multi_cloud_image.go
  rightscale/data_source_network.go
  rightscale/data_source_network_gateway.go
  rightscale/data_source_route_table.go
  rightscale/data_source_security_group.go
  rightscale/data_source_server.go
  rightscale/data_source_server_template.go
  rightscale/data_source_ssh_key.go
  rightscale/data_source_subnet.go
  rightscale/data_source_volume.go
  rightscale/data_source_volume_snapshot.go
  rightscale/data_source_volume_type.go
  rightscale/provider.go
  rightscale/resource.go
  rightscale/resource_credential.go
  rightscale/resource_cwf_process.go
  rightscale/resource_cwf_process_test.go
  rightscale/resource_deployment.go
  rightscale/resource_instance.go
  rightscale/resource_network.go
  rightscale/resource_network_gateway.go
  rightscale/resource_route.go
  rightscale/resource_route_table.go
  rightscale/resource_security_group.go
  rightscale/resource_security_group_rule.go
  rightscale/resource_server.go
  rightscale/resource_server_array.go
  rightscale/resource_ssh_key.go
  rightscale/resource_subnet.go
  website/docs/d/cm_cloud.markdown
  website/docs/d/cm_server.markdown
  website/docs/r/cm_instance.markdown
  website/docs/r/cm_server.markdown
  website/docs/r/cm_server_array.markdown
Labels: size/L

#3 Update changelog format
  CHANGELOG.md
Labels: size/XS

#5 Issue #4 - docs fix, add endquote
  CHANGELOG.md
  website/docs/d/cm_server.markdown
Labels: documentation, provider/rightscale, size/XS

#9 Issue #6 - fix links in doc
  CHANGELOG.md
  website/docs/d/cm_server.markdown
  website/docs/r/cm_server_array.markdown
Labels: documentation, provider/rightscale, size/XS

#8 Issue #7 - Fixes in doc index page
  CHANGELOG.md
  website/docs/index.html.markdown
Labels: documentation, provider/rightscale, size/XS
